//! ThinDom0 rootfs builder.
//!
//! Produces the cpio.gz that becomes the dom0 rootfs. This file is
//! split into pure renderers (testable today, no I/O) and an executor
//! (mmdebstrap + chroot + cpio shellouts; tested by actually running
//! install-thindom0 on a real host).
//!
//! Design choice — busybox-init, not systemd:
//!
//! The dom0's only job is to bring up Xen + run the cockpit. systemd
//! drags ~80 MB of dependencies into the cpio.gz; busybox + a single
//! /init script does everything we need (mount /proc /sys /dev /run,
//! load kernel modules, start xenstored + xenconsoled, exec cockpit
//! on tty1) in ~5 MB. Smaller cpio = faster cold boot, smaller blast
//! radius for security.
//!
//! Layout of the rootfs we build:
//!
//!   /init                    busybox shell, PID 1 (this file's
//!                            `render_init_script`)
//!   /usr/local/bin/rotten-apple   the cli + cockpit binary
//!   /etc/rotten-apple/active.toml the orchestrator's manifest input
//!   /etc/rotten-apple/user-desktop.toml  baked at install time
//!   /etc/inittab             busybox-init respawn config (tty1 = cockpit)
//!   /etc/group, /etc/passwd  minimal — root only
//!   /sbin, /bin              busybox + xen-tools (xl, xenstored, ...)
//!   /lib                     libxl + glibc + helpers
//!
//! The user_root_uuid is read from /proc/cmdline at boot — that's how
//! /init knows which device to share with the user-desktop guest.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use crate::thin_dom0_manifest::{
    USER_DESKTOP_MANIFEST_FILENAME,
    USER_DESKTOP_VISIBLE_MANIFEST_FILENAME,
};

/// Inputs to the rootfs builder. Caller picks which manifest file
/// to bake in (the user-desktop guest's TOML) and which rotten-apple
/// binary to copy in.
#[derive(Debug, Clone)]
pub struct RootfsSpec {
    /// Path to the rotten-apple binary that becomes /usr/local/bin/rotten-apple
    /// inside the cpio. Typically `/usr/local/bin/rotten-apple` from the
    /// host (the same binary running the install).
    pub rotten_apple_binary: PathBuf,
    /// Contents of /etc/rotten-apple/user-desktop.toml inside the cpio.
    /// Generated by `thin_dom0_manifest::render_user_desktop_manifest`.
    pub user_desktop_manifest: String,
    /// Contents of /etc/rotten-apple/user-desktop-visible.toml inside
    /// the cpio. Used by the recovery GRUB entry to keep the guest on
    /// a visible paravirtual display path during passphrase bring-up.
    pub user_desktop_visible_manifest: String,
    /// Kernel driver bound to the framebuffer GPU on the host being
    /// provisioned (e.g. "i915", "amdgpu", "nouveau"), as detected at
    /// install time. Drives which firmware blobs get bundled into the cpio
    /// so dom0 can light the panel — derived from the machine, not a
    /// hardcoded vendor list. None on a headless host (no firmware bundled).
    pub framebuffer_gpu_driver: Option<String>,
    /// Authorized SSH public keys to bake into /root/.ssh/authorized_keys
    /// in the cpio. dropbear listens on xenbr0; this is how the user
    /// reaches dom0 from inside the user-desktop guest after the iGPU
    /// passes through. Empty string disables SSH access (dom0 still
    /// reachable from cockpit on tty1 before/after the guest runs,
    /// just not while it's running with iGPU).
    pub authorized_ssh_keys: String,
    /// Path on the HOST where the cpio.gz is written. Typically
    /// /boot/rotten-apple/thin-dom0.cpio.gz.
    pub output_cpio: PathBuf,
    /// Workspace directory mmdebstrap uses to stage the rootfs before
    /// packing. Removed after pack. Typically /var/cache/rotten-apple/dom0-rootfs.
    pub workdir: PathBuf,
    /// Ubuntu suite to bootstrap (jammy/noble/resolute/...). Read verbatim
    /// from the host's /etc/os-release so the dom0 rootfs is ABI-matched and
    /// carries a Xen version that actually exists in that suite's repos.
    pub suite: String,
    /// Xen major.minor (e.g. "4.20") derived from the host's boot image,
    /// used to build the versioned xen-utils-<ver>/libxenmisc<ver> package
    /// names so they match what the suite's repos actually ship.
    pub xen_version: String,
    /// `mmdebstrap` mirror URL. Default: Ubuntu archive.
    pub mirror: String,
    /// Linux kernel release string (e.g. "6.17.0-23-generic") whose
    /// `/lib/modules/<release>/` tree gets copied into the cpio after
    /// mmdebstrap. Without this, dom0 boots without ANY loadable kernel
    /// modules — a problem because critical drivers like nvme,
    /// nvme_core, and i915 are =m on Ubuntu. With no nvme module dom0
    /// can't see the host's NVMe storage at all (mount_host_boot finds
    /// nothing to scan, persistent logs are silently dropped, the user-
    /// desktop guest can't open its disk image — 2026-05-07 lesson).
    /// Caller usually plugs in `uname -r` from the host; the cpio is
    /// implicitly version-locked to the kernel copy in /boot/rotten-apple.
    pub kernel_release: String,
}

impl RootfsSpec {
    /// Apt package list. Tight on purpose — busybox + xen-tools is
    /// nearly enough; the small additions are kernel-module helpers
    /// (kmod) and a libc.
    pub fn packages(&self) -> Vec<String> {
        let mut pkgs: Vec<String> = [
            "busybox-static",        // /init shell + 200 standard utils
            "kmod",                  // modprobe, depmod for xen-blkback etc.
            "xen-utils-common",      // xenstored, xenconsoled, xl
            "iproute2",              // ip + bridge for xenbr0
            "kbd",                   // setfont (cockpit needs it on tty1)
            "ca-certificates",       // ssl trust (image pulls etc.)
            "dropbear-bin",          // tiny ssh server — dom0 reachability after iGPU passthrough
            "isc-dhcp-client",       // dhclient on xenbr0 so dom0 has an IP guests can reach
            // udev intentionally NOT included: pulls systemd transitively
            // and ThinDom0 doesn't need it. cockpit reads /sys directly
            // for GPU + IOMMU enumeration; libxl uses xenstored, not udev.
        ]
        .iter()
        .map(|s| s.to_string())
        .collect();
        // Xen runtime — package names are version-suffixed (xen-utils-4.20,
        // libxenmisc4.20 on 26.04). The version is DERIVED from the host's
        // boot image at install time (see xen_version_from_image), not
        // hardcoded, so the dom0 rootfs always matches the host's Xen across
        // upgrades instead of failing mmdebstrap on a stale version string.
        pkgs.push(format!("xen-utils-{}", self.xen_version));
        pkgs.push(format!("libxenmisc{}", self.xen_version));
        pkgs
    }
}

/// The /init script the kernel runs as PID 1 after extracting the
/// cpio.gz into tmpfs. Pure: no I/O.
///
/// Hard rules — PID 1 dying = kernel panic = boot loop:
///   * NO `set -e` / `set -u` — any non-zero return from a sub-command
///     would otherwise kill init.
///   * Every risky command goes through `try` which logs but doesn't
///     fail PID 1.
///   * A recovery busybox shell spawns on tty2 BEFORE any risky work,
///     so even if everything else goes sideways the user can switch
///     with Ctrl-Alt-F2 to debug.
///   * The cockpit on tty1 sits in a respawn loop. If cockpit can't
///     start at all (binary missing, libs missing), we drop a busybox
///     shell on tty1 instead so the user sees something.
pub fn render_init_script() -> String {
    String::from(
r#"#!/bin/busybox sh
# /init — PID 1 in ThinDom0. Kernel extracts the cpio into tmpfs and
# execs us. PID 1 dying panics the kernel and reboots, so this script
# is paranoid: no `set -e`, every risky step is logged-but-non-fatal,
# and a recovery shell is always reachable on tty2.

# Logging sinks (set before any stage() call):
#   * /dev/console — visible if a framebuffer attaches. Under Xen PV
#     dom0 without /lib/modules for i915, no fb attaches and this is
#     a black hole. Keep writing anyway in case we eventually fix it.
#   * /tmp/init.log — tmpfs, lost on reboot. Useful while /init is
#     still running and the user has a recovery shell on tty2.
#   * $PERSIST_LOG — file on the host's /boot partition (unencrypted
#     ext4 by Ubuntu default). Set after mount_host_boot succeeds.
#     Survives reboot, so we can read it from FatDom0 after a black-
#     screen ThinDom0 boot. THIS is the new diagnostic path.
PERSIST_LOG=""
TMP_LOG=/tmp/init.log

stage() {
    msg="[init] $*"
    echo "$msg" > /dev/console 2>/dev/null
    echo "$msg" >> "$TMP_LOG" 2>/dev/null
    # Persist AND flush each milestone. A late hard reset (the Xen-level
    # bootloop) loses anything still in the page cache; ext4's 5s commit
    # was the only reason earlier hang-logs survived, and an early reset
    # beats that timer. A sync per logged step is irrelevant at boot.
    if [ -n "$PERSIST_LOG" ]; then
        echo "$msg" >> "$PERSIST_LOG" 2>/dev/null
        sync 2>/dev/null
    fi
}

# try(): run a command, log status, never propagate failure to PID 1.
# On failure, captures the command's stdout+stderr into both logs so
# we can see WHY a step failed, not just THAT it failed.
try() {
    desc="$1"; shift
    out=$("$@" 2>&1)
    rc=$?
    if [ $rc -eq 0 ]; then
        stage "ok    $desc"
    else
        stage "FAIL  $desc (rc=$rc)"
        {
            echo "--- try '$desc' failed (rc=$rc) ---"
            echo "$out"
            echo "---"
        } >> "$TMP_LOG" 2>/dev/null
        if [ -n "$PERSIST_LOG" ]; then
            {
                echo "--- try '$desc' failed (rc=$rc) ---"
                echo "$out"
                echo "---"
            } >> "$PERSIST_LOG" 2>/dev/null
        fi
    fi
}

# dump_xen_logs(): snapshot the Xen control-plane logs (in tmpfs, lost on
# reboot) PLUS `xl dmesg` — the Xen HYPERVISOR console ring, i.e. the very
# messages we cannot see on this laptop's black framebuffer. Called right
# before the cockpit handoff so a black-screen boot that gets that far still
# tells us, from disk, what Xen and dom0 actually did.
dump_xen_logs() {
    [ -n "$PERSIST_LOG" ] || return 0
    {
        echo "=== xl dmesg (Xen hypervisor console ring) ==="
        xl dmesg 2>/dev/null | tail -200
        echo "=== xen control-plane logs ==="
        for f in /var/log/xen/xenstored.log /var/log/xen/xenconsoled.log \
                 /var/log/dhclient.log /var/log/dropbear.log; do
            echo "--- $f ---"
            cat "$f" 2>/dev/null
        done
        echo "=== dmesg tail at handoff ==="
        dmesg 2>/dev/null | tail -120
    } >> "$PERSIST_LOG" 2>/dev/null
    sync 2>/dev/null
}

# mount_host_boot(): scan block devices for the host's boot filesystem
# and mount it RW at /boot-host. Accept both layouts we generate:
#   - separate /boot      -> /boot-host/rotten-apple/vmlinuz
#   - /boot on /          -> /boot-host/boot/rotten-apple/vmlinuz
# Robust across hardware: no UUID lookup (busybox
# mount may not support `-U`), no udev dependency (systemd-udevd is
# NOT in the cpio package list — udev was excluded to avoid pulling
# in systemd, see RootfsSpec::packages). Best-effort: returns 1 if
# nothing matches, callers fall back to /tmp-only logging.
mount_host_boot() {
    mkdir -p /boot-host
    # NVMe namespaces can take several SECONDS to enumerate after
    # `modprobe nvme` on real hardware — the sim's virtio scratch disk is
    # instant, which masked this for the whole project. A single scan that
    # runs before /dev/nvme0n1p* exists finds nothing, returns 1, and the
    # persistent log is NEVER created — dom0 then boots blind with no
    # forensic trail. CONFIRMED-SHAPE 2026-06-15: both ThinDom0 entries
    # HALTED at black (no reboot → dom0 did NOT crash, so unpack succeeded)
    # yet left NO new init log → /init ran but mount_host_boot didn't
    # succeed. So: poll for the boot device for ~20s, and `timeout`-wrap
    # each mount so a slow/half-enumerated device can't WEDGE PID 1 here
    # (a hang would also starve the GPU coldplug below → panel stays dark).
    _wait=0
    while [ "$_wait" -lt 20 ]; do
        for dev in /dev/nvme*n*p* /dev/sd*[0-9]* /dev/mmcblk*p* /dev/vd*[0-9]* /dev/xvd*[0-9]*; do
            [ -b "$dev" ] || continue
            if timeout 5 mount -t ext4 -o ro "$dev" /boot-host 2>/dev/null; then
                if [ -f /boot-host/rotten-apple/vmlinuz ] || \
                   [ -f /boot-host/boot/rotten-apple/vmlinuz ]; then
                    mount -o remount,rw /boot-host 2>/dev/null
                    return 0
                fi
                umount /boot-host 2>/dev/null
            fi
        done
        _wait=$((_wait + 1))
        sleep 1
    done
    return 1
}

stage "rotten-apple ThinDom0 /init starting"

# busybox shipped as a single binary; install symlinks for every applet
# so /bin/sh, /bin/mount, etc. work. Idempotent.
try "busybox install symlinks"  /bin/busybox --install -s /bin

# Early mounts. /proc and /sys must come before anything reads
# /proc/cmdline. devtmpfs auto-mount from the kernel may have run
# already (our config sets CONFIG_DEVTMPFS_MOUNT) — failures here
# are tolerated.
mkdir -p /proc /sys /dev /run /tmp
try "mount /proc"  mount -t proc     proc     /proc -o nodev,noexec,nosuid
try "mount /sys"   mount -t sysfs    sysfs    /sys  -o nodev,noexec,nosuid
try "mount /dev"   mount -t devtmpfs udev     /dev  -o mode=0755,nosuid
try "mount /run"   mount -t tmpfs    tmpfs    /run  -o mode=0755,nosuid,nodev
try "mount /tmp"   mount -t tmpfs    tmpfs    /tmp  -o nosuid,nodev
# /dev/pts and /dev/shm MUST be created AFTER the devtmpfs mount above:
# devtmpfs replaces the cpio's /dev wholesale, so any pts/shm dirs made
# beforehand are shadowed and these mounts fail ENOENT (confirmed in
# init-20260522-000049.log lines 7-14). Create them on the live devtmpfs.
mkdir -p /dev/pts /dev/shm
try "mount devpts" mount -t devpts   devpts   /dev/pts -o gid=5,mode=0620
try "mount /dev/shm" mount -t tmpfs  tmpfs    /dev/shm -o nodev,nosuid

# Spawn the recovery busybox shell on tty2 RIGHT NOW — before anything
# riskier than mounting tmpfs. If the rest of this script wedges or
# panics, Ctrl-Alt-F2 reaches the shell. setsid + own session so its
# signals don't propagate back to PID 1. Order matters: this used to
# spawn after modprobe nvme + mount_host_boot, but if either of those
# hangs or panics, the user lost the escape hatch (2026-05-07 lesson).
stage "spawning recovery shell on tty2"
(setsid -c /bin/busybox sh < /dev/tty2 > /dev/tty2 2>&1) &

# Storage drivers — Ubuntu ships these as =m, so without /lib/modules
# being copied into the cpio (build_rootfs step 2.5), modprobe fails
# and dom0 has zero block devices. Critical that these run BEFORE
# mount_host_boot — without nvme.ko, /dev/nvme*n*p* never exists, the
# scan finds nothing, and the persistent log path silently drops on
# the floor. Wrapped in `timeout 10` so a hung modprobe can't wedge
# /init forever (would manifest as a bootloop — kernel reboots when
# PID 1 stalls past kernel.hung_task_timeout).
try "modprobe nvme_core" timeout 10 modprobe nvme_core
try "modprobe nvme"      timeout 10 modprobe nvme
# Nested QEMU/Xen bring-up uses a virtio scratch disk for persistent
# logs. On real hardware these are usually absent and modprobe simply
# logs FAIL without hurting boot; in the simulator they are the
# difference between proving /init reached mount_host_boot vs. seeing
# an empty /dev tree and learning nothing.
try "modprobe virtio_pci" timeout 10 modprobe virtio_pci
try "modprobe virtio_blk" timeout 10 modprobe virtio_blk
try "modprobe virtio_scsi" timeout 10 modprobe virtio_scsi
try "modprobe sd_mod"      timeout 10 modprobe sd_mod

# xen-pciback — needed to honor `xen-pciback.hide=(<bdf>)` from the
# kernel cmdline. Without this module loaded, the hide directive is
# parsed but ignored: the framebuffer GPU stays bound to dom0's
# i915/simpledrm, libxl can't claim it for the guest, and the user-
# desktop guest launches with no display (no LUKS prompt, "thin gets
# lost" — 2026-05-07). Same `timeout 10` guard as above.
try "modprobe xen_pciback" timeout 10 modprobe xen_pciback
# devtmpfs auto-creates the device nodes, but the kernel needs a beat
# to enumerate the controller and namespaces. ~1s is plenty in
# practice; we're not chasing milliseconds at boot.
sleep 1

# Persistent forensics — must come AFTER /dev is mounted AND nvme
# is loaded but BEFORE anything risky. If we black-screen later,
# this is how we find out what happened.
if mount_host_boot; then
    LOG_DIR=/boot-host/rotten-apple/log
    mkdir -p "$LOG_DIR"
    PERSIST_LOG="$LOG_DIR/init-$(date +%Y%m%d-%H%M%S 2>/dev/null || echo unknown).log"
    {
        echo "=== rotten-apple ThinDom0 /init log ==="
        echo "kernel : $(uname -r 2>/dev/null)"
        echo "cmdline: $(cat /proc/cmdline 2>/dev/null)"
        echo "uptime : $(cat /proc/uptime 2>/dev/null)"
        echo "==="
        cat "$TMP_LOG" 2>/dev/null
        echo "=== dmesg snapshot at mount time ==="
        dmesg 2>/dev/null | tail -100
        echo "=== /dev block devices ==="
        ls -la /dev/nvme* /dev/sd* /dev/mmcblk* /dev/vd* /dev/xvd* 2>/dev/null
    } >> "$PERSIST_LOG" 2>/dev/null
    stage "persistent log: $PERSIST_LOG"
else
    stage "FAIL  could not mount host /boot for persistent log"
fi

# Light the panel. THE reason ThinDom0 black-screened for weeks: this is a
# udev-less busybox PID 1, so nothing autoloads the GPU driver the way a
# normal distro's coldplug (systemd-udevd) does. Under Xen PV the EFI/
# simpledrm console starves (Xen owns the EFI GOP handoff), so the ONLY
# thing that lights the laptop panel is the native KMS driver (i915/amdgpu/
# nouveau/...) binding the framebuffer GPU. We coldplug it by hand, the
# vendor-agnostic way: walk the PCI bus and modprobe whatever driver each
# device's modalias resolves to (modules.alias from the bundled /lib/modules
# answers). The firmware that driver needs was bundled at build time.
#
# This block MUST run after mount_host_boot: loading a KMS driver under Xen
# PV is the riskiest step in this script — an i915 DMA fault can wedge the
# MACHINE, not just the modprobe process, and `timeout 10` cannot save us
# from that. The pre-attempt stage line below is synced to disk first, so a
# boot that dies right here still names the device+driver that killed it.
# (2026-06-12 lesson: this used to run before the mount; an early wedge left
# NO log and was indistinguishable from a kernel that never booted.)
#
# dom0 owns the GPU at boot (cockpit is visible on the panel); handing it to
# a passthrough guest is a later, explicit step (the Parallels-style
# takeover), NOT done here.
for _dev in /sys/bus/pci/devices/*; do
    case "$(cat "$_dev/class" 2>/dev/null)" in
        0x03*|0x02*|0x0c03*)
            # 0x03 = display controller (lights the panel — the whole point),
            # 0x02 = network controller (a built-in wired NIC, if any),
            # 0x0c03 = USB controller (so a USB/dock NIC can enumerate later).
            # All need a hand-loaded driver in this udev-less init.
            _alias="$(cat "$_dev/modalias" 2>/dev/null)"
            if [ -n "$_alias" ]; then
                stage "coldplug ${_dev##*/} starting (if this is the last line, the driver wedged the machine)"
                try "coldplug ${_dev##*/}" timeout 10 modprobe -q "$_alias"
            fi
            ;;
    esac
done

# Parse /proc/cmdline for rotten_apple.* hints. Defaults to empty.
USER_ROOT_UUID=""
DOM0_PINNED_CPU=""
HIDE_PCI=""
BREAK_STAGE=""
COCKPIT_MANIFEST="/etc/rotten-apple/user-desktop.toml"
for tok in $(cat /proc/cmdline 2>/dev/null); do
    case "$tok" in
        rotten_apple.user_root_uuid=*)
            USER_ROOT_UUID="${tok#rotten_apple.user_root_uuid=}"
            ;;
        rotten_apple.dom0_pinned_cpu=*)
            DOM0_PINNED_CPU="${tok#rotten_apple.dom0_pinned_cpu=}"
            ;;
        rotten_apple.hide_pci=*)
            HIDE_PCI="${tok#rotten_apple.hide_pci=}"
            ;;
        rotten_apple.break=*)
            BREAK_STAGE="${tok#rotten_apple.break=}"
            ;;
        rotten_apple.cockpit_manifest=*)
            COCKPIT_MANIFEST="${tok#rotten_apple.cockpit_manifest=}"
            ;;
    esac
done
[ -n "$USER_ROOT_UUID"  ] && echo "$USER_ROOT_UUID"  > /run/rotten-apple.user_root_uuid
[ -n "$DOM0_PINNED_CPU" ] && echo "$DOM0_PINNED_CPU" > /run/rotten-apple.dom0_pinned_cpu
[ -n "$HIDE_PCI" ]        && echo "$HIDE_PCI"        > /run/rotten-apple.hide_pci
[ -n "$BREAK_STAGE" ]     && echo "$BREAK_STAGE"     > /run/rotten-apple.break
echo "$COCKPIT_MANIFEST" > /run/rotten-apple.cockpit_manifest
stage "cmdline: user_root_uuid=$USER_ROOT_UUID  dom0_pinned_cpu=$DOM0_PINNED_CPU  hide_pci=$HIDE_PCI  break=$BREAK_STAGE  cockpit_manifest=$COCKPIT_MANIFEST"

maybe_break() {
    want="$1"
    [ "$BREAK_STAGE" = "$want" ] || return 0
    stage "breakpoint hit: $want"
    try "sync logs before breakpoint" sync
    while true; do
        sleep 600
    done
}

# Simulator-only breakpoint: proves /init got through early mounts,
# storage-driver loading, persistent-log setup, and cmdline parsing
# before any Xen control-plane work starts.
maybe_break before-xen

# Hand the framebuffer GPU to xen-pciback so libxl can attach it to the
# user-desktop guest at create time. Done via sysfs because the kernel-
# native cmdline syntax `xen-pciback.hide=(BDF)` panics init with
# "syntax error unexpected '('" — the parens are interpreted as shell
# metacharacters (2026-05-07 bootloop). Skip cleanly when no BDF was
# passed (headless hosts, GPU detection failed, etc.).
if [ -n "$HIDE_PCI" ]; then
    stage "binding $HIDE_PCI to xen-pciback (sysfs)"
    # Both new_slot and bind paths exist after modprobe xen_pciback.
    # If the module isn't loaded these writes silently fail (try logs
    # them) — caller sees the FAIL and looks at /var/log/init log.
    try "pciback new_slot $HIDE_PCI" \
        sh -c "echo '$HIDE_PCI' > /sys/bus/pci/drivers/pciback/new_slot"
    try "pciback bind $HIDE_PCI" \
        sh -c "echo '$HIDE_PCI' > /sys/bus/pci/drivers/pciback/bind"
fi

# Xen control plane.
mkdir -p /var/run/xen /var/log/xen /var/lib/xen
# xen-gntdev/xen-gntalloc are LOAD-BEARING for xenstored: it maps the
# xenstore ring through the grant table, so without /dev/xen/gntdev the
# daemon dies on startup with "FATAL: Failed to open connection to gnttab:
# No such file or directory" — xenstore never comes up, and cockpit then
# launches with a DEAD control plane (cannot list or start any domain).
# A udev-less busybox init autoloads nothing, so these must be explicit.
# (xenfs gives /proc/xen; blkback/netback are the PV backends for guests.)
#
# xenstored opens THREE Xen char devices at startup — privcmd (built-in),
# /dev/xen/gntdev (xen_gntdev, grant table) and /dev/xen/evtchn
# (xen_evtchn, event channel). Miss either module and it dies FATAL before
# serving a single key. xen_gntalloc pairs with gntdev for guest grants.
#
# `-a` IS LOAD-BEARING. `modprobe mod1 mod2 mod3` does NOT load three
# modules — it loads mod1 and treats mod2/mod3 as module PARAMETERS to it
# ("xen_blkback: unknown parameter 'xen_gntdev' ignored"). Without -a this
# line silently loaded ONLY xen_blkback for the life of the project;
# xen_netback/xenfs/gntdev/evtchn never loaded, so xenstored died on the
# missing grant table / event channel and cockpit ran with a dead control
# plane. Confirmed 2026-06-12 by QEMU-sim differential (one missing module
# surfaced per re-sim: gnttab → evtchn).
try "modprobe xen mods" modprobe -a xen_blkback xen_netback xenfs xen_gntdev xen_gntalloc xen_evtchn
try "mount xenfs"       mount -t xenfs xenfs /proc/xen
stage "starting xenstored"
xenstored --no-fork </dev/null >/var/log/xen/xenstored.log 2>&1 &
# Poll for xenstore readiness instead of a blind `sleep 1`. The untimed
# `xl vcpu-pin` below historically wedged PID 1 because it ran before
# xenstore could answer; wait up to ~10s for a real response.
xs_ready=0
xs_i=0
while [ $xs_i -lt 10 ]; do
    if xenstore-exists / >/dev/null 2>&1 || xenstore-read / >/dev/null 2>&1; then
        xs_ready=1; break
    fi
    sleep 1
    xs_i=$((xs_i + 1))
done
stage "xenstore ready=$xs_ready (waited ${xs_i}s)"
stage "starting xenconsoled"
xenconsoled --pid-file /run/xenconsoled.pid </dev/null >/var/log/xen/xenconsoled.log 2>&1 &

# Pin dom0 to its assigned E-core (skipped if cmdline didn't carry one).
# `timeout` guard is LOAD-BEARING: on the real laptop this xl call blocks
# indefinitely connecting to xenstore (xenstored not ready after the blind
# `sleep 1` above, or a deadlock), wedging PID 1 inside `try` right after
# "starting xenconsoled" so cockpit never launches — the black-screen
# "thindom doesn't boot". CONFIRMED 2026-05-22 by QEMU-sim differential: the
# sim omits dom0_pinned_cpu and sails past here to the cockpit handoff; the
# laptop passes dom0_pinned_cpu=N and hangs exactly here. The pin is an
# E-core optimization — never worth wedging the whole boot. Same `timeout`
# protection the modprobes above already use.
if [ -n "$DOM0_PINNED_CPU" ]; then
    try "pin dom0 vcpu" timeout 10 xl vcpu-pin Domain-0 0 "$DOM0_PINNED_CPU"
fi

# Network bridge for guests + DHCP for dom0 (so guest can SSH in).
try "create xenbr0"   ip link add name xenbr0 type bridge
try "xenbr0 up"       ip link set xenbr0 up
stage "dhclient xenbr0 (background)"
(dhclient xenbr0 -nw </dev/null >/var/log/dhclient.log 2>&1) &

# Dropbear host keys + daemon for SSH-from-guest after iGPU passthrough.
mkdir -p /etc/dropbear /root/.ssh
chmod 700 /root/.ssh 2>/dev/null
try "dropbear ed25519 host key" \
    sh -c '[ -f /etc/dropbear/dropbear_ed25519_host_key ] || \
           dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key'
try "dropbear ecdsa host key" \
    sh -c '[ -f /etc/dropbear/dropbear_ecdsa_host_key ] || \
           dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key'
stage "starting dropbear"
(dropbear -R -s -E -p 22 </dev/null >/var/log/dropbear.log 2>&1) &

# dom0 memory governor: dom0 booted high enough to unpack the initramfs into
# RAM; hand that headroom back now by ballooning dom0 down to its steady floor,
# and let it grow again on guest/pressure demand. Backgrounded so it can never
# wedge the cockpit handoff; xenstored is already up so its `xl` calls work. A
# dead governor just means dom0 holds its boot size (safe) — so no respawn.
if [ -x /usr/local/bin/rotten-apple ]; then
    stage "starting dom0 memory governor"
    (setsid -c /usr/local/bin/rotten-apple dom0-memd >/var/log/dom0-memd.log 2>&1) &
fi

dump_xen_logs
stage "init complete — handing off to cockpit on tty1"

# Cockpit on tty1 in a respawn loop. If the cockpit binary itself is
# broken (missing libs, etc.), respawning helps nothing — fall through
# to a busybox shell on tty1 after 3 consecutive crashes within ~10s.
COCKPIT_FAILS=0
while true; do
    if [ ! -x /usr/local/bin/rotten-apple ]; then
        stage "rotten-apple binary missing — dropping busybox shell on tty1"
        setsid -c /bin/busybox sh < /dev/tty1 > /dev/tty1 2>&1
        sleep 2
        continue
    fi
    setsid -c /usr/local/bin/rotten-apple cockpit \
        --manifest "$COCKPIT_MANIFEST" \
        < /dev/tty1 > /dev/tty1 2>&1
    rc=$?
    stage "cockpit exited rc=$rc"
    COCKPIT_FAILS=$((COCKPIT_FAILS + 1))
    if [ $COCKPIT_FAILS -ge 3 ] && [ $rc -ne 0 ]; then
        stage "cockpit failed 3+ times — dropping busybox shell on tty1"
        setsid -c /bin/busybox sh < /dev/tty1 > /dev/tty1 2>&1
        COCKPIT_FAILS=0
    fi
    sleep 2
done
"#)
}

/// Path on the HOST where /etc/rotten-apple/active.toml gets baked.
/// The cpio.gz contents include this. Active.toml describes dom0 itself.
#[allow(dead_code)]
pub fn render_active_manifest_for_dom0() -> String {
    String::from(
r#"# rotten-apple dom0 active manifest — baked into the ThinDom0 cpio.gz.
# This describes dom0's role to the orchestrator (who is running inside
# dom0). NOT a guest manifest — the guest manifest lives in
# /etc/rotten-apple/user-desktop.toml alongside.
[profile]
name = "rotten-apple-dom0"
schema_version = "1"
description = "Thin dom0 — orchestrator + cockpit. No daily-driver workloads."
type = "service"

[meta]
license = "personal"

[resources]
memory_active   = "2048M"
memory_idle     = "1024M"
memory_minimum  = "768M"
vcpus_active    = 2
vcpus_idle      = 1
vcpus_minimum   = 1
prefer_p_cores  = false
idle_on_e_cores = true

[storage]
root = { kind = "block", source = "/dev/ram0", mode = "ro" }

[network]
mode = "bridge"
[[network.interfaces]]
name = "primary"
mac = "auto"
egress = "any"

[gpu]
mode = "none"

[tpm]
mode = "none"

[orchestration]
priority = "background"
"#)
}

/// Argv to invoke mmdebstrap with. Returns a Vec so the caller can
/// `Command::new("mmdebstrap").args(&args)`. Pure — no I/O.
pub fn mmdebstrap_args(spec: &RootfsSpec) -> Vec<String> {
    let mut packages = spec.packages().iter().map(|s| s.to_string()).collect::<Vec<_>>().join(",");
    packages.insert(0, ' '); // separator
    let _ = packages.trim();
    let mut args = vec![
        "--variant=minbase".to_string(),
        format!("--include={}", spec.packages().join(",")),
        // Architecture defaults to host; mmdebstrap detects automatically.
        "--mode=auto".to_string(),
        spec.suite.clone(),
        spec.workdir.to_string_lossy().to_string(),
        spec.mirror.clone(),
    ];
    // mmdebstrap also accepts --components for non-main repos. Ubuntu's
    // xen-* lives in main + universe; include both.
    args.insert(0, "--components=main,universe".to_string());
    args
}

/// Argv to pack `workdir` into a cpio.gz at `output_cpio`. Run from
/// inside `workdir` (caller cd's into it). The `cpio` invocation is
/// gzipped via shell pipe — the executor sets up the pipe.
pub fn cpio_pack_command(workdir: &Path, output_cpio: &Path) -> String {
    // `find . | cpio -o -H newc | gzip -9` is the canonical way to
    // produce a kernel-readable initrd. -H newc = the format Linux's
    // initramfs extractor expects.
    format!(
        "cd {workdir} && find . | cpio --quiet -o -H newc | gzip -9 > {out}",
        workdir = workdir.display(),
        out = output_cpio.display(),
    )
}

// ---------------------------------------------------------------------------
// Executor — actually builds the rootfs. Not unit-tested (requires
// mmdebstrap, network, root); shipped behind install-thindom0's
// pre-flight so failures surface clearly.

#[derive(Debug)]
pub enum RootfsError {
    PreFlight(String),
    Step { step: &'static str, detail: String },
}

impl std::fmt::Display for RootfsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RootfsError::PreFlight(s) => write!(f, "rootfs pre-flight: {s}"),
            RootfsError::Step { step, detail } => write!(f, "rootfs step '{step}': {detail}"),
        }
    }
}

impl std::error::Error for RootfsError {}

/// Build the dom0 cpio.gz from `spec`. Returns the cpio.gz path.
/// Creates `spec.workdir` (wiping any existing contents), invokes
/// mmdebstrap, bakes in the rotten-apple binary + /init + manifests,
/// then packs as cpio.gz. Side effects all live under `spec.workdir`
/// and `spec.output_cpio`; nothing else on the host is touched.
/// Bundle the firmware blobs the framebuffer GPU's driver needs into the
/// cpio at /lib/firmware, derived from the machine being provisioned rather
/// than a hardcoded vendor list. Asks the detected driver (i915/amdgpu/...)
/// which firmware it references via `modinfo -F firmware`, scoped to the
/// exact kernel whose modules we bundled, and copies only those files (in
/// whatever compressed variant the host ships). A headless host (no driver),
/// a builtin driver, or a missing blob is a no-op, not an error — we'd
/// rather boot than refuse to build.
fn bundle_gpu_firmware(spec: &RootfsSpec) -> Result<(), RootfsError> {
    use std::process::Command;
    use std::path::Path;
    let log = |msg: String| eprintln!("    [rootfs/firmware] {msg}");

    let driver = match spec.framebuffer_gpu_driver.as_deref() {
        Some(d) if !d.is_empty() => d,
        _ => {
            log("no framebuffer GPU driver detected — PV/headless display, \
                 skipping firmware".to_string());
            return Ok(());
        }
    };

    let dst_root = spec.workdir.join("lib/firmware");

    // Primary path: GPU drivers keep all their firmware variants under
    // /lib/firmware/<driver>/ (i915, amdgpu, nouveau all do). Copy the whole
    // subtree so we cannot miss the specific blob this panel's hardware needs.
    // modinfo's MODULE_FIRMWARE list is deliberately INCOMPLETE for i915 — it
    // declares only some DMC versions while the driver selects the matching
    // one at runtime from an internal table (observed: 18 DMC entries in
    // modinfo vs 38 on disk). cp -a preserves the compressed (.zst) form the
    // kernel decompresses at load.
    let driver_fw_dir = Path::new("/lib/firmware").join(driver);
    if driver_fw_dir.is_dir() {
        std::fs::create_dir_all(&dst_root).map_err(|e| RootfsError::Step {
            step: "mkdir /lib/firmware", detail: e.to_string(),
        })?;
        let cp = Command::new("cp").arg("-a").arg(&driver_fw_dir).arg(&dst_root).output()
            .map_err(|e| RootfsError::Step {
                step: "cp -a /lib/firmware/<driver>", detail: e.to_string(),
            })?;
        if !cp.status.success() {
            return Err(RootfsError::Step {
                step: "cp -a /lib/firmware/<driver>",
                detail: format!("exit={}\nstderr: {}", cp.status,
                    String::from_utf8_lossy(&cp.stderr)),
            });
        }
        let n = std::fs::read_dir(&driver_fw_dir).map(|d| d.count()).unwrap_or(0);
        log(format!("→ /lib/firmware/{driver} ({n} blobs, full subtree)"));
        return Ok(());
    }

    // Fallback for a driver that does NOT use a same-named firmware dir: ask
    // modinfo what it references and copy those files (with their compressed
    // variants), scoped to the kernel whose modules we bundled. Builtin /
    // firmware-less drivers yield an empty list = nothing to bundle.
    let referenced: Vec<String> = match Command::new("modinfo")
        .arg("-k").arg(&spec.kernel_release)
        .arg("-F").arg("firmware").arg(driver).output()
    {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .lines().map(str::trim).filter(|l| !l.is_empty()).map(String::from).collect(),
        _ => Vec::new(),
    };
    if referenced.is_empty() {
        log(format!("{driver}: no /lib/firmware/{driver} dir and modinfo lists \
                     no firmware — nothing to bundle"));
        return Ok(());
    }
    let fw_root = Path::new("/lib/firmware");
    let mut copied = 0usize;
    for rel in &referenced {
        let base = fw_root.join(rel);
        let candidates = [
            base.clone(),
            PathBuf::from(format!("{}.zst", base.display())),
            PathBuf::from(format!("{}.xz", base.display())),
            PathBuf::from(format!("{}.gz", base.display())),
        ];
        let Some(src) = candidates.into_iter().find(|p| p.exists()) else { continue };
        let dst_rel = src.strip_prefix(fw_root).unwrap_or_else(|_| Path::new(rel));
        let dst = dst_root.join(dst_rel);
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent).map_err(|e| RootfsError::Step {
                step: "mkdir /lib/firmware subdir", detail: e.to_string(),
            })?;
        }
        if Command::new("cp").arg("-a").arg(&src).arg(&dst).output()
            .map(|o| o.status.success()).unwrap_or(false) { copied += 1; }
    }
    log(format!("→ /lib/firmware for {driver}: {copied}/{} referenced blobs (fallback)",
                referenced.len()));
    Ok(())
}

/// The kernel modules a ThinDom0 actually loads — the seeds whose full
/// dependency closure (and ONLY that closure) we bundle into the cpio,
/// instead of the entire ~190 MiB `/lib/modules/<kver>/kernel` tree. The
/// detected framebuffer GPU driver (e.g. i915/amdgpu) is appended at
/// runtime from `RootfsSpec::framebuffer_gpu_driver`.
///
/// Why each: storage (mount the host /boot for logs + see guest disks);
/// ext4 (mount_host_boot does `mount -t ext4`); the xen_* control-plane
/// set (xenstored needs gntdev/evtchn, guests need blk/netback, passthrough
/// needs pciback — see render_init_script); bridge (xenbr0); xhci (USB/dock
/// NIC enumeration); a spread of wired + USB-ethernet NIC drivers so a dock
/// or dongle brings up dom0's SSH escape hatch; virtio_* so the QEMU
/// bring-up harness ([[project_thindom0_qemu_simulator]]) still works.
/// Anything not in a seed's dep chain is simply absent — modprobe of an
/// unmatched modalias in /init fails gracefully (it's wrapped in `try`).
const DOM0_SEED_MODULES: &[&str] = &[
    // storage + root fs
    "nvme", "nvme_core", "sd_mod", "ext4",
    // xen control plane + PV backends + passthrough (must match /init)
    "xen_blkback", "xen_netback", "xenfs",
    "xen_gntdev", "xen_gntalloc", "xen_evtchn", "xen_pciback",
    // networking: bridge for xenbr0, AF_PACKET for dhclient
    "bridge", "af_packet",
    // USB host controllers (dock / USB-NIC enumeration)
    "xhci_pci", "xhci_hcd",
    // input: internal PS/2 keyboard (i8042/atkbd) + USB HID keyboards, so
    // the cockpit's VT/stdin actually gets key events. Without these the
    // kernel delivers zero keystrokes and crossterm's event::read() on tty1
    // sees nothing — a dead cockpit. i2c_hid_acpi covers newer Dell/laptop
    // internal keyboards wired over I2C instead of PS/2.
    "i8042", "atkbd", "serio_raw",
    "usbhid", "hid", "hid_generic",
    "i2c_hid", "i2c_hid_acpi",
    // wired NICs (common Intel/Realtek laptop + dock)
    "e1000e", "igc", "igb", "r8169",
    // USB-ethernet (dock dongles)
    "r8152", "cdc_ether", "usbnet", "asix", "ax88179_178a",
    // virtio (QEMU sim scratch disk + net)
    "virtio_pci", "virtio_blk", "virtio_scsi", "virtio_net",
];

/// Parse `modprobe --show-depends` for `module` under `kver` into the set of
/// absolute `.ko[.zst]` host paths it needs (the module itself + every
/// dependency, in load order). Returns empty for builtin/unknown/missing
/// modules (modprobe errors or emits only `builtin` lines) — the caller
/// tolerates that, since the seed list is deliberately broad.
fn module_dep_files(module: &str, kver: &str) -> Vec<PathBuf> {
    use std::process::Command;
    let out = Command::new("modprobe")
        .arg("--show-depends")
        .arg("--set-version").arg(kver)
        .arg(module)
        .output();
    let out = match out {
        Ok(o) if o.status.success() => o,
        _ => return Vec::new(),
    };
    String::from_utf8_lossy(&out.stdout)
        .lines()
        // lines look like: `insmod /lib/modules/<kver>/kernel/.../foo.ko.zst`
        .filter_map(|l| l.strip_prefix("insmod "))
        .filter_map(|rest| rest.split_whitespace().next())
        .map(PathBuf::from)
        .collect()
}

/// Bundle ONLY the modules a thin dom0 needs (the closure of
/// `DOM0_SEED_MODULES` + the detected GPU driver) into the cpio, then
/// regenerate modules.dep/alias against that slimmed set with `depmod -b`.
///
/// Replaces a wholesale `cp -a /lib/modules/<kver>` (~190 MiB) — which made
/// the cpio 264 MiB compressed / 461 MiB unpacked. That fat initrd was the
/// common root of two boot failures: dom0_mem unpack OOM, and GRUB's ext4
/// driver stalling for minutes on a >4-extent initrd (a 264 MiB file can't
/// hold fewer than ~3 extents and re-fragments on every write). A ~30-50
/// MiB slim initrd is a single extent, loads instantly, and unpacks in
/// well under 1 GiB. See [[project_thindom0_boot_wedge]].
fn bundle_kernel_modules(spec: &RootfsSpec) -> Result<(), RootfsError> {
    use std::process::Command;
    let log = |msg: String| eprintln!("    [rootfs/modules] {msg}");
    let kver = &spec.kernel_release;
    let host_modules = PathBuf::from(format!("/lib/modules/{kver}"));
    if !host_modules.exists() {
        return Err(RootfsError::PreFlight(format!(
            "host has no /lib/modules/{kver} — kernel-modules package missing or \
             wrong release; without it dom0 can't see NVMe/SCSI storage")));
    }

    let mut seeds: Vec<String> = DOM0_SEED_MODULES.iter().map(|s| s.to_string()).collect();
    if let Some(drv) = &spec.framebuffer_gpu_driver {
        seeds.push(drv.clone());
    }

    let mut files: BTreeSet<PathBuf> = BTreeSet::new();
    for m in &seeds {
        for f in module_dep_files(m, kver) {
            files.insert(f);
        }
    }
    // Sanity floor: if dependency resolution produced almost nothing, the
    // host tooling (modprobe/modules.dep) is broken — fail loudly rather
    // than ship a cpio with no storage drivers (silent unbootable dom0).
    if files.len() < 5 {
        return Err(RootfsError::PreFlight(format!(
            "kernel-module dependency resolution yielded only {} files for {kver}; \
             expected dozens. Is modules.dep present (run depmod)? Refusing to \
             build a cpio with no storage/xen drivers.", files.len())));
    }

    let dst_modules = spec.workdir.join(format!("lib/modules/{kver}"));
    std::fs::create_dir_all(&dst_modules).map_err(|e| RootfsError::Step {
        step: "mkdir /lib/modules/<kver>", detail: e.to_string(),
    })?;

    // Copy each resolved .ko preserving its path under the workdir. `cp -a
    // --parents <abs> <workdir>` recreates <workdir>/lib/modules/<kver>/...
    let mut cp = Command::new("cp");
    cp.arg("-a").arg("--parents");
    for f in &files {
        cp.arg(f);
    }
    cp.arg(&spec.workdir);
    let cp_out = cp.output().map_err(|e| RootfsError::Step {
        step: "cp -a --parents <modules>", detail: e.to_string(),
    })?;
    if !cp_out.status.success() {
        return Err(RootfsError::Step {
            step: "cp -a --parents <modules>",
            detail: format!("exit={}\nstderr: {}",
                cp_out.status, String::from_utf8_lossy(&cp_out.stderr)),
        });
    }

    // depmod needs the builtin/order metadata to resolve builtin symbols;
    // copy it best-effort (absent on some kernels), then regenerate
    // modules.dep + modules.alias from JUST the .ko files we copied so
    // modprobe and the /init modalias coldplug stay consistent.
    for meta in ["modules.builtin", "modules.builtin.modinfo", "modules.order"] {
        let p = host_modules.join(meta);
        if p.exists() {
            let _ = Command::new("cp").arg("-a").arg("--parents").arg(&p)
                .arg(&spec.workdir).output();
        }
    }
    let depmod = Command::new("depmod")
        .arg("-b").arg(&spec.workdir).arg(kver)
        .output()
        .map_err(|e| RootfsError::Step { step: "depmod -b", detail: e.to_string() })?;
    if !depmod.status.success() {
        return Err(RootfsError::Step {
            step: "depmod -b",
            detail: format!("exit={}\nstderr: {}",
                depmod.status, String::from_utf8_lossy(&depmod.stderr)),
        });
    }

    log(format!(
        "→ /lib/modules/{kver} (slim: {} .ko from {} seeds, vs whole-tree ~190 MiB)",
        files.len(), seeds.len()));
    Ok(())
}

pub fn build_rootfs(spec: &RootfsSpec, dry_run: bool) -> Result<PathBuf, RootfsError> {
    use std::process::Command;

    let log = |step: &str, msg: String| {
        eprintln!("    [rootfs/{step}] {msg}");
    };

    // Pre-flight: existence of the binary we'll bake in matters even
    // for dry-runs (the user wants to know if the plan is going to
    // hit a wall). Tool availability (mmdebstrap, cpio) is a real-run
    // concern only — flagging it in dry-run mode would prevent users
    // from previewing the install before they have the tools installed.
    if !spec.rotten_apple_binary.exists() {
        return Err(RootfsError::PreFlight(format!(
            "rotten-apple binary {} does not exist", spec.rotten_apple_binary.display())));
    }

    if dry_run {
        let warn = |t: &str| if which(t).is_none() {
            log("preflight", format!("warning — `{t}` not on PATH; \
                                     `apt install {t}` before --execute"));
        };
        warn("mmdebstrap");
        warn("cpio");
        log("plan", format!("would mmdebstrap {} -> {}",
                            spec.suite, spec.workdir.display()));
        log("plan", format!("would bake {} -> {}/usr/local/bin/rotten-apple",
                            spec.rotten_apple_binary.display(),
                            spec.workdir.display()));
        log("plan", format!("would pack {} -> {}",
                            spec.workdir.display(),
                            spec.output_cpio.display()));
        return Ok(spec.output_cpio.clone());
    }

    if which("mmdebstrap").is_none() {
        return Err(RootfsError::PreFlight(
            "mmdebstrap not found on PATH — install with `apt install mmdebstrap`".into()));
    }
    if which("cpio").is_none() {
        return Err(RootfsError::PreFlight(
            "cpio not found on PATH — install with `apt install cpio`".into()));
    }

    // 1. Fresh workdir.
    if spec.workdir.exists() {
        std::fs::remove_dir_all(&spec.workdir).map_err(|e| RootfsError::Step {
            step: "clean workdir",
            detail: format!("rm -rf {}: {e}", spec.workdir.display()),
        })?;
    }
    std::fs::create_dir_all(&spec.workdir).map_err(|e| RootfsError::Step {
        step: "create workdir",
        detail: format!("mkdir -p {}: {e}", spec.workdir.display()),
    })?;
    log("workdir", format!("→ {}", spec.workdir.display()));

    // 2. mmdebstrap.
    let args = mmdebstrap_args(spec);
    log("mmdebstrap", format!("mmdebstrap {}", args.join(" ")));
    let out = Command::new("mmdebstrap").args(&args).output()
        .map_err(|e| RootfsError::Step { step: "mmdebstrap spawn",
            detail: format!("{e}") })?;
    if !out.status.success() {
        return Err(RootfsError::Step {
            step: "mmdebstrap",
            detail: format!("exit={}\nstderr: {}",
                out.status, String::from_utf8_lossy(&out.stderr)),
        });
    }

    // 2.5. Bundle ONLY the kernel modules a thin dom0 needs (the closure of
    // DOM0_SEED_MODULES + the detected GPU driver), not the whole ~190 MiB
    // /lib/modules/<kver>/kernel tree. The fat tree made the cpio 264 MiB /
    // 461 MiB unpacked, which caused both the dom0_mem unpack OOM and GRUB's
    // >4-extent ext4 load stall. See bundle_kernel_modules + boot_wedge memory.
    bundle_kernel_modules(spec)?;

    // 2.6. Bundle the firmware the framebuffer GPU's driver needs — derived
    // from the machine being provisioned, NOT a hardcoded vendor matrix. The
    // driver was detected at install time (i915/amdgpu/nouveau/...); we ask
    // it which blobs it references and pull exactly those. Without the
    // display engine's firmware (e.g. i915 DMC/GuC), the driver binds but the
    // panel stays dark — the other half of the ThinDom0 black-screen story
    // (the /init `modprobe <driver>` is the first half).
    bundle_gpu_firmware(spec)?;

    // 3. Bake in rotten-apple binary at /usr/local/bin/rotten-apple.
    let dst_bin = spec.workdir.join("usr/local/bin/rotten-apple");
    if let Some(parent) = dst_bin.parent() {
        std::fs::create_dir_all(parent).map_err(|e| RootfsError::Step {
            step: "mkdir /usr/local/bin", detail: e.to_string(),
        })?;
    }
    std::fs::copy(&spec.rotten_apple_binary, &dst_bin).map_err(|e| RootfsError::Step {
        step: "copy rotten-apple",
        detail: format!("{} -> {}: {e}", spec.rotten_apple_binary.display(), dst_bin.display()),
    })?;
    set_executable(&dst_bin)?;
    log("bake", format!("→ {}", dst_bin.display()));

    // 4. /init script.
    let init = spec.workdir.join("init");
    std::fs::write(&init, render_init_script()).map_err(|e| RootfsError::Step {
        step: "write /init", detail: e.to_string(),
    })?;
    set_executable(&init)?;
    log("bake", format!("→ {}", init.display()));

    // 5. Manifests.
    let etc_dir = spec.workdir.join("etc/rotten-apple");
    std::fs::create_dir_all(&etc_dir).map_err(|e| RootfsError::Step {
        step: "mkdir /etc/rotten-apple", detail: e.to_string(),
    })?;
    std::fs::write(etc_dir.join("active.toml"), render_active_manifest_for_dom0())
        .map_err(|e| RootfsError::Step {
            step: "write active.toml", detail: e.to_string(),
        })?;
    std::fs::write(
        etc_dir.join(USER_DESKTOP_MANIFEST_FILENAME),
        &spec.user_desktop_manifest,
    )
        .map_err(|e| RootfsError::Step {
            step: "write user-desktop.toml", detail: e.to_string(),
        })?;
    std::fs::write(
        etc_dir.join(USER_DESKTOP_VISIBLE_MANIFEST_FILENAME),
        &spec.user_desktop_visible_manifest,
    )
        .map_err(|e| RootfsError::Step {
            step: "write user-desktop-visible.toml", detail: e.to_string(),
        })?;
    log("bake", format!(
        "→ {}/active.toml + {} + {}",
        etc_dir.display(),
        USER_DESKTOP_MANIFEST_FILENAME,
        USER_DESKTOP_VISIBLE_MANIFEST_FILENAME,
    ));

    // 5b. SSH authorized_keys — the user reaches dom0 from inside the
    // user-desktop guest via dropbear once iGPU passthrough makes the
    // dom0 console invisible.
    let ssh_dir = spec.workdir.join("root/.ssh");
    std::fs::create_dir_all(&ssh_dir).map_err(|e| RootfsError::Step {
        step: "mkdir /root/.ssh", detail: e.to_string(),
    })?;
    let auth = ssh_dir.join("authorized_keys");
    std::fs::write(&auth, &spec.authorized_ssh_keys).map_err(|e| RootfsError::Step {
        step: "write authorized_keys", detail: e.to_string(),
    })?;
    // chmod 600 — sshd refuses world-readable authorized_keys
    use std::os::unix::fs::PermissionsExt;
    let mut perm = std::fs::metadata(&auth).map_err(|e| RootfsError::Step {
        step: "stat authorized_keys", detail: e.to_string(),
    })?.permissions();
    perm.set_mode(0o600);
    std::fs::set_permissions(&auth, perm).map_err(|e| RootfsError::Step {
        step: "chmod authorized_keys", detail: e.to_string(),
    })?;
    if !spec.authorized_ssh_keys.is_empty() {
        let n_keys = spec.authorized_ssh_keys.lines().filter(|l| !l.trim().is_empty()).count();
        log("bake", format!("→ {} ({n_keys} SSH key(s))", auth.display()));
    } else {
        log("bake", format!("→ {} (empty — dom0 SSH disabled)", auth.display()));
    }

    // 6. Output dir for the cpio.
    if let Some(parent) = spec.output_cpio.parent() {
        std::fs::create_dir_all(parent).map_err(|e| RootfsError::Step {
            step: "mkdir output dir", detail: format!("{}: {e}", parent.display()),
        })?;
    }

    // 7. Pack as cpio.gz.
    let pack_cmd = cpio_pack_command(&spec.workdir, &spec.output_cpio);
    log("cpio", pack_cmd.clone());
    let out = Command::new("sh").args(["-c", &pack_cmd]).output()
        .map_err(|e| RootfsError::Step { step: "cpio pack spawn", detail: e.to_string() })?;
    if !out.status.success() {
        return Err(RootfsError::Step {
            step: "cpio pack",
            detail: format!("exit={}\nstderr: {}",
                out.status, String::from_utf8_lossy(&out.stderr)),
        });
    }

    let size_kb = std::fs::metadata(&spec.output_cpio)
        .map(|m| m.len() / 1024).unwrap_or(0);
    log("pack", format!("→ {} ({size_kb} KB)", spec.output_cpio.display()));

    Ok(spec.output_cpio.clone())
}

fn set_executable(path: &Path) -> Result<(), RootfsError> {
    use std::os::unix::fs::PermissionsExt;
    let mut perm = std::fs::metadata(path).map_err(|e| RootfsError::Step {
        step: "stat for chmod", detail: format!("{}: {e}", path.display()),
    })?.permissions();
    perm.set_mode(0o755);
    std::fs::set_permissions(path, perm).map_err(|e| RootfsError::Step {
        step: "chmod 755", detail: format!("{}: {e}", path.display()),
    })?;
    Ok(())
}

fn which(name: &str) -> Option<PathBuf> {
    std::env::var_os("PATH")?.to_string_lossy()
        .split(':')
        .map(|d| PathBuf::from(d).join(name))
        .find(|p| p.exists())
}

// ---------------------------------------------------------------------------
// Tests

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_spec() -> RootfsSpec {
        RootfsSpec {
            rotten_apple_binary: PathBuf::from("/usr/local/bin/rotten-apple"),
            user_desktop_manifest: String::from("# stub user-desktop manifest"),
            user_desktop_visible_manifest: String::from("# stub visible-debug manifest"),
            framebuffer_gpu_driver: None,
            authorized_ssh_keys: String::from("ssh-ed25519 AAAA...stub user@example\n"),
            output_cpio: PathBuf::from("/boot/rotten-apple/thin-dom0.cpio.gz"),
            workdir: PathBuf::from("/var/cache/rotten-apple/dom0-rootfs"),
            suite: "noble".to_string(),
            xen_version: "4.20".to_string(),
            mirror: "http://archive.ubuntu.com/ubuntu".to_string(),
            kernel_release: "6.17.0-23-generic".to_string(),
        }
    }

    #[test]
    fn package_list_is_thin() {
        // ThinDom0 lives in RAM at boot — every extra MB increases
        // cold-boot time. Pin a soft cap so a future change doesn't
        // accidentally drag in systemd or x11.
        let spec = sample_spec();
        let pkgs = spec.packages();
        let has = |name: &str| pkgs.iter().any(|p| p == name);
        assert!(pkgs.len() <= 14,
                "package list should stay under ~14 ({} got)", pkgs.len());
        assert!(has("busybox-static"), "busybox is the floor");
        assert!(has("xen-utils-common"), "xen control plane required");
        assert!(has("xen-utils-4.20"),
                "versioned xen-utils derived from host (sample = 4.20)");
        assert!(has("dropbear-bin"),
                "dropbear required for dom0 ssh access after iGPU passthrough");
        assert!(!has("systemd"), "systemd is forbidden in ThinDom0 — use busybox-init");
        assert!(!has("udev"), "udev pulls systemd; ThinDom0 reads /sys directly via cockpit");
        assert!(!has("openssh-server"),
                "use dropbear instead of openssh-server (smaller, faster)");
    }

    #[test]
    fn init_script_does_not_use_set_e() {
        // PID 1 dying = kernel panic = boot loop. Pin: the script never
        // sets `-e`/`-eu` so a single non-zero subprocess return doesn't
        // kill init. Every risky step goes through the `try` helper
        // which logs but doesn't propagate failure.
        let s = render_init_script();
        for line in s.lines() {
            let trimmed = line.trim();
            assert!(!trimmed.starts_with("set -e"),
                    "init script must never set -e (PID 1 dying = boot loop): {line:?}");
            assert!(!trimmed.starts_with("set -u"),
                    "init script must never set -u: {line:?}");
        }
    }

    #[test]
    fn init_script_spawns_recovery_shell_on_tty2() {
        // If anything goes wrong post-mount, the user must be able to
        // Ctrl-Alt-F2 to a busybox shell. Pin that the recovery shell
        // is spawned BEFORE EVERY risky step — including modprobe and
        // mount_host_boot. The 2026-05-07 bootloop happened because
        // recovery was spawned AFTER modprobe nvme; if modprobe hung
        // or panicked, the user had no escape hatch.
        let s = render_init_script();
        let recovery_pos = s.find("setsid -c /bin/busybox sh < /dev/tty2")
            .expect("init must spawn recovery shell on tty2");
        let modprobe_pos = s.find("try \"modprobe nvme_core\"")
            .expect("init must call modprobe nvme_core via try");
        let mount_pos = s.find("if mount_host_boot;")
            .expect("init must call mount_host_boot");
        let xenstored_pos = s.find("xenstored --no-fork")
            .expect("init must start xenstored");
        assert!(recovery_pos < modprobe_pos,
                "recovery shell on tty2 must spawn BEFORE modprobe \
                 (so a hung/panicking modprobe doesn't lock the user \
                 out): recovery@{recovery_pos} modprobe@{modprobe_pos}");
        assert!(recovery_pos < mount_pos,
                "recovery shell must spawn BEFORE mount_host_boot \
                 (block-device scan can hang on broken hardware)");
        assert!(recovery_pos < xenstored_pos,
                "recovery shell must spawn BEFORE xenstored \
                 (xenstored can deadlock on broken xenstore state)");
    }

    #[test]
    fn init_script_coldplugs_gpu_after_persistent_log_mount() {
        // Loading a KMS driver under Xen PV can wedge the whole machine
        // (i915 DMA fault), not just the modprobe process. The 2026-06-12
        // black boot left NO init log because the coldplug ran before
        // mount_host_boot — the wedge was indistinguishable from a kernel
        // that never booted. Pin: PERSIST_LOG must be live (and a synced
        // pre-attempt stage written) before any GPU modprobe.
        let s = render_init_script();
        let mount_pos = s.find("if mount_host_boot;")
            .expect("init must call mount_host_boot");
        let coldplug_pos = s.find("0x03*")
            .expect("init must coldplug display-class PCI devices");
        assert!(mount_pos < coldplug_pos,
                "GPU coldplug must run AFTER mount_host_boot so a \
                 machine-wedging driver load still leaves a synced log \
                 line: mount@{mount_pos} coldplug@{coldplug_pos}");
        assert!(s.contains("starting (if this is the last line"),
                "coldplug must write a synced pre-attempt stage line \
                 before the modprobe: {s}");
    }

    #[test]
    fn init_script_loads_gntdev_for_xenstored() {
        // xenstored maps the xenstore ring through the grant table; without
        // xen-gntdev it dies on startup ("FATAL: Failed to open connection
        // to gnttab") and cockpit comes up with a dead control plane. A
        // udev-less busybox init autoloads nothing, so the grant-table
        // modules MUST be in the explicit modprobe line, BEFORE xenstored.
        // Confirmed 2026-06-12 by QEMU-sim differential.
        let s = render_init_script();
        // Anchor on the real `modprobe -a` command (the line that loads the
        // xen control-plane modules), so we inspect the actual command and
        // catch the param-swallowing form.
        let cmd_pos = s.find("modprobe -a xen_blkback")
            .expect("xen control-plane load must use `modprobe -a` — without \
                     it, modprobe loads only the first module and treats the \
                     rest as bogus parameters (xenstored then dies on no \
                     gnttab)");
        let xenstored_pos = s.find("xenstored --no-fork")
            .expect("init must start xenstored");
        let line_end = s[cmd_pos..].find('\n').unwrap() + cmd_pos;
        let modprobe_line = &s[cmd_pos..line_end];
        assert!(modprobe_line.contains("xen_gntdev"),
                "xen control-plane modprobe must load xen_gntdev (xenstored \
                 needs the grant table): {modprobe_line:?}");
        assert!(modprobe_line.contains("xen_gntalloc"),
                "xen control-plane modprobe must load xen_gntalloc: \
                 {modprobe_line:?}");
        assert!(modprobe_line.contains("xen_evtchn"),
                "xen control-plane modprobe must load xen_evtchn (xenstored \
                 opens /dev/xen/evtchn too): {modprobe_line:?}");
        assert!(cmd_pos < xenstored_pos,
                "gntdev must load BEFORE xenstored starts");
    }

    #[test]
    fn init_script_starts_dropbear_and_dhcp() {
        // Caveat: once iGPU passes through to the user-desktop guest,
        // dom0 has no display. The escape hatch is SSH from inside
        // the guest. /init must bring up dom0's IP on xenbr0 (so the
        // guest can reach it) AND start the SSH server with
        // password auth disabled (key-only).
        let s = render_init_script();
        assert!(s.contains("dhclient xenbr0"),
                "/init must bring up dom0's IP on xenbr0: {s}");
        assert!(s.contains("dropbear "),
                "/init must start dropbear: {s}");
        assert!(s.contains("-s "),
                "dropbear must run with -s (password auth disabled): {s}");
    }

    #[test]
    fn init_script_starts_with_busybox_shebang() {
        // The cpio is extracted before any libc is reachable; only
        // busybox is guaranteed runnable. /init must use the explicit
        // busybox shebang so it works even if /bin/sh isn't a symlink
        // yet (we install the symlinks ourselves on the next line).
        let s = render_init_script();
        assert!(s.starts_with("#!/bin/busybox sh\n"),
                "init must use busybox shebang: {}", &s[..40]);
    }

    #[test]
    fn init_script_mounts_filesystems() {
        // /proc and /sys must be up before /proc/cmdline is read.
        // Pin the order: proc, sysfs, devtmpfs, tmpfs.
        let s = render_init_script();
        let proc_pos  = s.find("mount -t proc").expect("proc mount");
        let sysfs_pos = s.find("mount -t sysfs").expect("sysfs mount");
        let dev_pos   = s.find("mount -t devtmpfs").expect("devtmpfs mount");
        assert!(proc_pos < sysfs_pos);
        assert!(sysfs_pos < dev_pos);
    }

    #[test]
    fn init_script_extracts_user_root_uuid_from_cmdline() {
        // The whole point of passing user_root_uuid on the kernel
        // cmdline (vs. baking it into the cpio) is that updates to
        // the user's disk layout don't require a cpio rebuild. Pin
        // /init knows how to read it.
        let s = render_init_script();
        assert!(s.contains("rotten_apple.user_root_uuid="),
                "init must parse user_root_uuid from /proc/cmdline");
        assert!(s.contains("/run/rotten-apple.user_root_uuid"),
                "init must drop the UUID where the cockpit can find it");
    }

    #[test]
    fn init_script_supports_simulator_breakpoint_before_xen() {
        // Simulator-first bring-up needs a test-only checkpoint that
        // proves /init got through storage discovery and persistent-log
        // setup before Xen services muddy the trace. Pin the cmdline
        // parser, /run handoff, and the actual before-xen hook.
        let s = render_init_script();
        assert!(s.contains("rotten_apple.break="),
                "init must parse rotten_apple.break from /proc/cmdline: {s}");
        assert!(s.contains("/run/rotten-apple.break"),
                "init must expose the requested breakpoint under /run: {s}");
        assert!(s.contains("maybe_break before-xen"),
                "init must honor the before-xen simulator breakpoint: {s}");
        assert!(s.contains("breakpoint hit: $want"),
                "breakpoint helper must leave a visible stage marker: {s}");
    }

    #[test]
    fn init_script_brings_up_xen_control_plane() {
        // Without xenstored, libxl returns "Cannot connect to xenstore"
        // and no domain operation works. Pin xenstored + xenconsoled
        // are both spawned.
        let s = render_init_script();
        assert!(s.contains("xenstored"),  "init must start xenstored");
        assert!(s.contains("xenconsoled"), "init must start xenconsoled");
    }

    #[test]
    fn init_script_runs_cockpit_in_respawn_loop() {
        // PID 1 must never exit — kernel panics if it does. Earlier
        // rev used `exec setsid cockpit` which would panic the kernel
        // on cockpit crash. Respawn loop keeps /init alive.
        let s = render_init_script();
        assert!(s.contains("while true; do"),
                "init must wrap cockpit in a respawn loop: {s}");
        assert!(s.contains("/usr/local/bin/rotten-apple cockpit"),
                "init must run rotten-apple cockpit, not a shell");
        assert!(s.contains("/dev/tty1"),
                "cockpit must claim tty1");
    }

    #[test]
    fn init_script_passes_user_desktop_manifest() {
        // [c]/[n] in the cockpit defaults to creating whatever the
        // --manifest argument names. Pin: it's the user-desktop guest
        // TOML so first-boot create is the daily driver.
        let s = render_init_script();
        assert!(s.contains("COCKPIT_MANIFEST=\"/etc/rotten-apple/user-desktop.toml\""),
                "init must default cockpit to the daily-driver guest manifest: {s}");
        assert!(s.contains("--manifest \"$COCKPIT_MANIFEST\""),
                "cockpit must read its manifest path from the parsed cmdline: {s}");
    }

    #[test]
    fn init_script_can_override_cockpit_manifest_from_cmdline() {
        let s = render_init_script();
        assert!(s.contains("rotten_apple.cockpit_manifest="),
                "init must parse a cockpit manifest override from cmdline: {s}");
        assert!(s.contains("/run/rotten-apple.cockpit_manifest"),
                "init should expose the selected manifest path under /run: {s}");
    }

    #[test]
    fn init_script_pins_dom0_to_e_core() {
        // The whole point of dom0_pinned_cpu was to keep dom0 off the
        // P-cores. Pin /init actually applies the pin via xl vcpu-pin.
        let s = render_init_script();
        assert!(s.contains("xl vcpu-pin Domain-0"),
                "init must pin dom0 vcpus: {s}");
        assert!(s.contains("/run/rotten-apple.dom0_pinned_cpu"),
                "init must read the pin target from /run: {s}");
    }

    #[test]
    fn init_script_binds_pci_via_sysfs_not_cmdline_parens() {
        // 2026-05-07: my first PCI-passthrough wiring used the kernel-
        // blessed `xen-pciback.hide=(BDF)` cmdline syntax. The parens
        // got parsed as shell metacharacters by initramfs/init and
        // panicked PID 1 with "syntax error unexpected '('" — bootloop
        // (well-known issue, see Alpine forum). Switched to passing
        // `rotten_apple.hide_pci=BDF` (no parens) on the cmdline and
        // doing the bind via sysfs at runtime in /init. Pin both:
        // the cmdline parser sees our token, AND the sysfs bind path
        // is the one we use.
        let s = render_init_script();
        assert!(s.contains("rotten_apple.hide_pci="),
                "init must parse rotten_apple.hide_pci from cmdline: {s}");
        assert!(s.contains("/sys/bus/pci/drivers/pciback/new_slot"),
                "init must write BDF to pciback new_slot via sysfs: {s}");
        assert!(s.contains("/sys/bus/pci/drivers/pciback/bind"),
                "init must write BDF to pciback bind via sysfs: {s}");
        // Pin we did NOT regress to the parens approach somewhere
        // else in /init. Only check non-comment lines — the prose
        // comment legitimately mentions the avoided syntax.
        for line in s.lines() {
            let trimmed = line.trim_start();
            if trimmed.starts_with('#') { continue; }
            assert!(!line.contains("xen-pciback.hide=("),
                    "init must NOT use xen-pciback.hide=(...) syntax \
                     in any executable line — the parens panic init: \
                     {line:?}");
        }
    }

    #[test]
    fn init_script_modprobes_xen_pciback_for_passthrough() {
        // The dom0 kernel cmdline carries `xen-pciback.hide=(<bdf>)`
        // for the framebuffer GPU. Without xen_pciback.ko loaded, the
        // hide directive is silently ignored and libxl can't attach
        // the device to the user-desktop guest at create time —
        // libxl returns "device not assignable" and the guest boots
        // with no display (no visible LUKS prompt). Pin: /init does
        // `modprobe xen_pciback` early, with a `timeout` guard so a
        // hung modprobe can't wedge PID 1 into a bootloop.
        let s = render_init_script();
        let modprobe_pos = s.find("try \"modprobe xen_pciback\"")
            .expect("init must call modprobe xen_pciback via try");
        // Must use timeout wrapper — same hang-protection rationale
        // as the nvme modprobes above.
        let line = s.lines().find(|l| l.contains("modprobe xen_pciback"))
            .expect("xen_pciback modprobe line");
        assert!(line.contains("timeout"),
                "modprobe xen_pciback must be wrapped in timeout to \
                 protect against bootloop on hung modprobe: {line}");
        // Should run AFTER nvme modprobes (so the storage-modules block
        // is contiguous and ordered) but BEFORE mount_host_boot (so
        // we don't have a half-initialised pci subsystem when the
        // mount + later xen control plane try to enumerate devices).
        let nvme_pos = s.find("try \"modprobe nvme_core\"")
            .expect("nvme_core modprobe present");
        let mount_pos = s.find("if mount_host_boot;")
            .expect("mount_host_boot present");
        assert!(nvme_pos < modprobe_pos,
                "xen_pciback modprobe must be after the nvme block \
                 (storage modules go first)");
        assert!(modprobe_pos < mount_pos,
                "xen_pciback modprobe must be before mount_host_boot");
    }

    #[test]
    fn init_script_modprobes_nvme_before_mount_host_boot() {
        // CONFIG_BLK_DEV_NVME=m on Ubuntu — without modprobe nvme,
        // /dev/nvme*n*p* never exists in dom0 and mount_host_boot has
        // nothing to scan. We saw this fail for real on 2026-05-07
        // (no logs were written despite mount_host_boot being wired,
        // because nvme.ko wasn't loaded so the device tree was empty).
        // Pin: storage drivers are modprobed BEFORE mount_host_boot
        // runs, with a settle sleep so devtmpfs has time to create
        // the device nodes.
        let s = render_init_script();

        let nvme_core_pos = s.find("modprobe nvme_core")
            .expect("init must modprobe nvme_core");
        let nvme_pos = s.find("modprobe nvme\"")
            .or_else(|| s.find("modprobe nvme "))
            .expect("init must modprobe nvme");
        let virtio_pos = s.find("modprobe virtio_blk")
            .expect("init must modprobe virtio_blk for simulator disk visibility");
        let mount_pos = s.find("if mount_host_boot;")
            .expect("init must call mount_host_boot");

        assert!(nvme_core_pos < nvme_pos,
                "nvme_core must load before nvme: {s}");
        assert!(nvme_pos < virtio_pos,
                "virtio drivers must load after the nvme block but before mount_host_boot: {s}");
        assert!(virtio_pos < mount_pos,
                "virtio block support must be ready BEFORE mount_host_boot \
                 so the simulator scratch disk can carry persistent logs: {s}");
        assert!(nvme_pos < mount_pos,
                "nvme must be modprobed BEFORE mount_host_boot — \
                 otherwise /dev/nvme* doesn't exist and the scan \
                 finds nothing (2026-05-07 silent-log-drop bug): {s}");

        // Settle sleep gives devtmpfs time to create the nodes after
        // the kernel enumerates the controller.
        let settle = &s[nvme_pos..mount_pos];
        assert!(settle.contains("sleep "),
                "must sleep between nvme modprobe and mount_host_boot \
                 so devtmpfs can create the device nodes: {settle}");
    }

    #[test]
    fn init_script_mounts_host_boot_for_persistent_logs() {
        // Under Xen PV dom0 without /lib/modules for i915, /dev/console
        // can be a black hole — we get zero visible output even with
        // loglevel=7 (2026-05-07 black-screen regression). Without
        // forensics we can't tell whether dom0 panicked, /init wedged,
        // or cockpit crashed silently. Fix: /init scans block devices
        // for the host's /boot partition (matched by the
        // /rotten-apple/vmlinuz marker file we put there during lift)
        // and tees stage()/try() output to a timestamped log file
        // that survives reboot — readable from FatDom0 afterwards.
        // Pin all the moving parts.
        let s = render_init_script();

        // The mount helper exists and uses the marker-file approach
        // (no UUID lookup, no udev dependency). It must handle both
        // supported host layouts: separate /boot and /boot-on-/.
        assert!(s.contains("mount_host_boot()"),
                "init must define mount_host_boot helper: {s}");
        assert!(s.contains("/boot-host/rotten-apple/vmlinuz"),
                "mount_host_boot must verify the host /boot via the \
                 vmlinuz marker file (not by UUID — busybox mount \
                 may not support -U, and udev isn't in the cpio): {s}");
        assert!(s.contains("/boot-host/boot/rotten-apple/vmlinuz"),
                "mount_host_boot must also handle /boot-on-rootfs hosts: {s}");
        assert!(s.contains("/dev/nvme") && s.contains("/dev/sd")
                && s.contains("/dev/mmcblk") && s.contains("/dev/vd")
                && s.contains("/dev/xvd"),
                "mount_host_boot must scan all common block-device \
                 naming schemes (nvme, sd, mmcblk, vd, xvd): {s}");

        // Persistent log path is set after the mount, not before.
        let mount_pos = s.find("if mount_host_boot;")
            .expect("init must conditionally set PERSIST_LOG");
        let log_pos = s.find("LOG_DIR=/boot-host/rotten-apple/log")
            .expect("init must set LOG_DIR under /boot-host");
        assert!(mount_pos < log_pos,
                "PERSIST_LOG must be configured AFTER mount succeeds: {s}");

        // stage() writes to all three sinks (console, /tmp, persistent).
        assert!(s.contains("PERSIST_LOG=\"\""),
                "init must declare PERSIST_LOG empty by default: {s}");
        // stage() guards the persistent write behind `if [ -n "$PERSIST_LOG" ]`
        // and follows it with a `sync` so a late hard reset can't lose the
        // last milestone (the multi-line form replaced the old single-line
        // `&&` tee when per-step flushing was added).
        assert!(s.contains("if [ -n \"$PERSIST_LOG\" ]; then")
                && s.contains("echo \"$msg\" >> \"$PERSIST_LOG\""),
                "stage() must tee output to PERSIST_LOG (guarded) when set: {s}");

        // The boot-host mount happens AFTER /dev mount but BEFORE
        // anything risky (xenstored, xenconsoled, dropbear).
        let dev_mount_pos = s.find("mount -t devtmpfs")
            .expect("init must mount /dev");
        // Match the daemon launch specifically — `dump_xen_logs()` references
        // /var/log/xen/xenstored.log earlier in the script, so a bare
        // s.find("xenstored") would match the log path, not the daemon start.
        let xenstored_pos = s.find("xenstored --no-fork")
            .expect("init must start the xenstored daemon");
        assert!(dev_mount_pos < mount_pos,
                "mount_host_boot must run AFTER /dev is mounted: {s}");
        assert!(mount_pos < xenstored_pos,
                "mount_host_boot must run BEFORE risky xen control \
                 plane startup so we have logs of any xenstored \
                 failure: {s}");

        // The header dumped at the top of the persistent log carries
        // enough context to debug a black-screen boot from FatDom0.
        assert!(s.contains("rotten-apple ThinDom0 /init log"),
                "persistent log must carry an identifying header: {s}");
        assert!(s.contains("$(uname -r"),
                "persistent log header must capture kernel version: {s}");
        assert!(s.contains("$(cat /proc/cmdline"),
                "persistent log header must capture cmdline: {s}");
    }

    #[test]
    fn mmdebstrap_args_include_required_packages() {
        let spec = sample_spec();
        let args = mmdebstrap_args(&spec);
        let inc = args.iter().find(|a| a.starts_with("--include="))
            .expect("must have --include arg");
        assert!(inc.contains("busybox-static"),  "include list missing busybox: {inc}");
        assert!(inc.contains("xen-utils-common"), "include list missing xen-utils: {inc}");
    }

    #[test]
    fn mmdebstrap_args_include_universe() {
        // Ubuntu's xen-utils packages live in main, but the kernel
        // headers and a few helpers we may pull are in universe. Pin
        // we always pass --components=main,universe so apt finds them.
        let spec = sample_spec();
        let args = mmdebstrap_args(&spec);
        assert!(args.iter().any(|a| a == "--components=main,universe"),
                "mmdebstrap args must include both main and universe: {args:?}");
    }

    #[test]
    fn mmdebstrap_args_carry_suite_and_workdir() {
        let spec = sample_spec();
        let args = mmdebstrap_args(&spec);
        assert!(args.iter().any(|a| a == &spec.suite),
                "args must include the suite");
        assert!(args.iter().any(|a| a == &spec.workdir.to_string_lossy().to_string()),
                "args must include the workdir as the target");
    }

    #[test]
    fn cpio_pack_command_uses_newc_format_and_gzip() {
        // The kernel's initramfs extractor only understands cpio's
        // "newc" format. Plain cpio output (-H bin / no flag) silently
        // fails to extract. Pin the flag.
        let cmd = cpio_pack_command(
            Path::new("/var/cache/rotten-apple/dom0-rootfs"),
            Path::new("/boot/rotten-apple/thin-dom0.cpio.gz"),
        );
        assert!(cmd.contains("-H newc"),
                "cpio must use newc format (other formats fail to extract): {cmd}");
        assert!(cmd.contains("| gzip"),
                "output must be gzipped (multiboot2 module2 expects .gz): {cmd}");
        assert!(cmd.contains("/boot/rotten-apple/thin-dom0.cpio.gz"),
                "output path must appear in the command: {cmd}");
    }

    #[test]
    fn active_manifest_for_dom0_parses() {
        // The dom0 manifest is also a Profile — must validate through
        // the manifest crate. Pin: don't drift away from a parseable shape.
        let m = render_active_manifest_for_dom0();
        let p = rotten_apple_manifest::Profile::from_str(&m)
            .expect("dom0 active manifest must parse");
        assert_eq!(p.name(), "rotten-apple-dom0");
    }
}
