//! ThinDom0 native-EFI boot path — xen.efi on the ESP.
//!
//! WHY THIS EXISTS (2026-07-08 root cause): GRUB 2.14 release broke
//! multiboot2 on x86_64 EFI — GRUB takes a page fault inside its own
//! relocator at the final `boot` handoff, BEFORE Xen executes a single
//! instruction. Symptom: the menuentry's echo lines print, then the
//! machine freezes silently (firmware eats the #PF; laptop panels show
//! nothing). Upstream fix patches were posted to grub-devel 2026-05-13
//! (mail-archive msg43110/43111) but are merged nowhere; Ubuntu
//! resolute's 2.14-2ubuntu1/2 predates them. The 2026-05-27 unattended
//! upgrade from the working 2.14~git20250718 snapshot to the 2.14
//! release is what killed every ThinDom0 boot after May 21 — weeks of
//! kernel/cpio/dom0_mem bisection were chasing artifacts that never
//! mattered.
//!
//! The escape hatch is Xen's native EFI entry point: xen.efi is a
//! normal EFI application the firmware (or GRUB `chainloader`, which
//! uses firmware LoadImage/StartImage — no GRUB relocator) can run
//! directly. xen.efi reads a `xen.cfg` next to itself naming the dom0
//! kernel, ramdisk, and cmdlines, then boots dom0 exactly like the
//! multiboot2 path would have.
//!
//! Layout staged by `stage_esp()` (all inside the ESP, never touching
//! Ubuntu's /EFI/ubuntu — sacred rule):
//!
//!   /boot/efi/EFI/xen/xen.efi           ← copy of /boot/xen-*.efi (pkg)
//!   /boot/efi/EFI/xen/vmlinuz           ← copy of the staged dom0 kernel
//!   /boot/efi/EFI/xen/initrd.cpio.gz    ← copy of the staged dom0 rootfs
//!   /boot/efi/EFI/xen/xen.cfg           ← rendered here
//!
//! These are COPIES of /boot/rotten-apple/* — lift re-stages them on
//! every run so the ESP can't silently go stale (the manual bring-up
//! copy of 2026-07-08 had exactly that failure mode).
//!
//! xen.cfg has two sections: `thindom0` (default; autostart path) and
//! `recovery` (sync_console/noreboot Xen flags, hvc0 dom0 console,
//! rotten_apple.no_autostart=1). GRUB entries select a section by
//! passing its name as the argument after the chainloaded image path
//! (xen.efi takes the first non-option argument as the section name);
//! the raw NVRAM entry gets the default section.

use std::path::{Path, PathBuf};

use crate::thin_dom0_grub::{GrubEntryInputs, dom0_kernel_cmdline, xen_options_cmdline};

/// ESP-relative directory (also the GRUB/NVRAM path prefix, in
/// backslash form for efibootmgr).
pub const ESP_XEN_DIR: &str = "EFI/xen";
/// Label of the NVRAM boot entry we manage. Also the needle used to
/// detect an existing entry — change it and stale entries multiply.
pub const NVRAM_ENTRY_LABEL: &str = "rotten-apple Xen (native EFI)";

/// Render xen.cfg. Pure — no I/O. Cmdlines come from the SAME builders
/// as the GRUB multiboot2 entries so the two boot paths cannot drift.
///
/// Format reference: xen.efi's config parser (xen/common/efi/boot.c) —
/// INI-ish sections; `options=` is the hypervisor cmdline; `kernel=`
/// is "<filename> <dom0 cmdline...>"; `ramdisk=` a filename. Paths are
/// relative to xen.efi's own directory. No "placeholder" first token
/// anywhere — that is a multiboot convention, not an EFI one.
pub fn render_xen_cfg(g: &GrubEntryInputs) -> String {
    let xen_normal    = xen_options_cmdline(g, false);
    let xen_recovery  = xen_options_cmdline(g, true);
    let dom0_normal   = dom0_kernel_cmdline(g, false);
    let dom0_recovery = dom0_kernel_cmdline(g, true);
    format!(
        "# Generated by rotten-apple bootstrapper. Do not edit by hand — re-run\n\
         # `sudo rotten-apple lift` to regenerate. Read by xen.efi at boot.\n\
         [global]\n\
         default=thindom0\n\
         \n\
         [thindom0]\n\
         options={xen_normal}\n\
         kernel=vmlinuz {dom0_normal}\n\
         ramdisk=initrd.cpio.gz\n\
         \n\
         [recovery]\n\
         options={xen_recovery}\n\
         kernel=vmlinuz {dom0_recovery}\n\
         ramdisk=initrd.cpio.gz\n")
}

/// Walk `/proc/self/mountinfo` for the partition mounted at /boot/efi.
/// Returns `None` on BIOS hosts (no ESP mounted) — callers then skip
/// the whole native-EFI path and GRUB keeps its multiboot2 entries.
pub fn esp_mount_device_from_mountinfo(mountinfo: &str) -> Option<PathBuf> {
    for line in mountinfo.lines() {
        let mut parts = line.split(" - ");
        let pre  = parts.next().unwrap_or("");
        let post = parts.next();
        if pre.split_whitespace().nth(4) != Some("/boot/efi") {
            continue;
        }
        let post = post?;
        let mut after = post.split_whitespace();
        let _fstype = after.next()?;
        let device  = after.next()?;
        return Some(PathBuf::from(device));
    }
    None
}

/// Does efibootmgr's output already carry OUR entry pointing at OUR
/// loader path? Label match alone is not enough — a stale entry left
/// pointing somewhere else must be treated as absent (we then create a
/// fresh one; firmware tolerates duplicate labels, and the stale one is
/// reported for manual cleanup rather than auto-deleted — we never
/// delete NVRAM entries we can't prove we created).
pub fn nvram_has_current_entry(efibootmgr_output: &str) -> bool {
    efibootmgr_output.lines().any(|l|
        l.contains(NVRAM_ENTRY_LABEL) && l.contains("\\EFI\\xen\\xen.efi"))
}

/// Extract the BootOrder line's value ("0003,0000,...") so entry
/// creation can restore it verbatim — `efibootmgr -c` PREPENDS the new
/// entry to BootOrder, which would make Xen the firmware default and
/// violate the sacred rule (Ubuntu must stay the default boot).
pub fn boot_order_value(efibootmgr_output: &str) -> Option<String> {
    efibootmgr_output.lines()
        .find_map(|l| l.strip_prefix("BootOrder: "))
        .map(|s| s.trim().to_string())
}

/// Everything `stage_esp` needs. Split from ThinDom0Plan so the staging
/// logic is testable against a tempdir-shaped ESP.
#[derive(Debug, Clone)]
pub struct EspStageInputs {
    /// Mountpoint of the ESP (normally /boot/efi).
    pub esp_mount: PathBuf,
    /// Source of the hypervisor EFI image, e.g. /boot/xen-4.20-amd64.efi
    /// (dropped by xen-hypervisor-*-amd64 next to the .gz).
    pub xen_efi_source: PathBuf,
    /// The staged dom0 kernel (/boot/rotten-apple/vmlinuz) — already
    /// written by the kernel-copy step before this runs.
    pub kernel_source: PathBuf,
    /// The staged dom0 rootfs (/boot/rotten-apple/thin-dom0.cpio.gz).
    pub initrd_source: PathBuf,
}

#[derive(Debug)]
pub struct EspStageError(pub String);

impl std::fmt::Display for EspStageError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "ESP staging failed: {}", self.0)
    }
}
impl std::error::Error for EspStageError {}

/// Copy xen.efi + dom0 kernel + dom0 rootfs onto the ESP and write the
/// rendered xen.cfg beside them. Idempotent — plain overwrites; FAT has
/// no atomic rename worth chasing and the files are only read at boot.
pub fn stage_esp(
    inputs: &EspStageInputs,
    xen_cfg: &str,
    dry_run: bool,
) -> Result<(), EspStageError> {
    let dir = inputs.esp_mount.join(ESP_XEN_DIR);
    let copies: [(&Path, &str); 3] = [
        (&inputs.xen_efi_source, "xen.efi"),
        (&inputs.kernel_source,  "vmlinuz"),
        (&inputs.initrd_source,  "initrd.cpio.gz"),
    ];
    if dry_run {
        for (src, name) in copies {
            eprintln!("    [esp] would copy {} -> {}",
                      src.display(), dir.join(name).display());
        }
        eprintln!("    [esp] would write {} ({} bytes)",
                  dir.join("xen.cfg").display(), xen_cfg.len());
        return Ok(());
    }
    std::fs::create_dir_all(&dir).map_err(|e|
        EspStageError(format!("mkdir {}: {e}", dir.display())))?;
    for (src, name) in copies {
        let dst = dir.join(name);
        std::fs::copy(src, &dst).map_err(|e| EspStageError(format!(
            "copy {} -> {}: {e}", src.display(), dst.display())))?;
        eprintln!("    [esp] {} -> {}", src.display(), dst.display());
    }
    let cfg_path = dir.join("xen.cfg");
    std::fs::write(&cfg_path, xen_cfg).map_err(|e|
        EspStageError(format!("write {}: {e}", cfg_path.display())))?;
    eprintln!("    [esp] xen.cfg -> {}", cfg_path.display());
    Ok(())
}

/// Ensure the firmware has a boot entry for \EFI\xen\xen.efi WITHOUT
/// touching BootOrder (Ubuntu stays the default; the Xen entry is
/// picked via the firmware's one-shot menu, `efibootmgr -n`, or by the
/// GRUB chainload entries which don't need NVRAM at all). Best-effort:
/// a host without efivars (chroot, container, BIOS) gets a warning,
/// never a failed lift — the GRUB chainload path works regardless.
pub fn ensure_nvram_entry(esp_disk: &Path, esp_partition: u32, dry_run: bool) {
    use std::process::Command;
    let log = |msg: String| eprintln!("    [nvram] {msg}");
    if dry_run {
        log(format!("would ensure entry {NVRAM_ENTRY_LABEL:?} -> \\EFI\\xen\\xen.efi \
                     on {} part {esp_partition} (BootOrder untouched)", esp_disk.display()));
        return;
    }
    let current = match Command::new("efibootmgr").output() {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).to_string(),
        Ok(o) => {
            log(format!("efibootmgr exit={} — skipping NVRAM entry (GRUB \
                         chainload entries still work): {}",
                        o.status, String::from_utf8_lossy(&o.stderr).trim()));
            return;
        }
        Err(e) => {
            log(format!("efibootmgr unavailable ({e}) — skipping NVRAM entry \
                         (GRUB chainload entries still work)"));
            return;
        }
    };
    if nvram_has_current_entry(&current) {
        log(format!("entry {NVRAM_ENTRY_LABEL:?} already present — OK"));
        return;
    }
    let order_before = boot_order_value(&current);
    let created = Command::new("efibootmgr")
        .args(["-c", "-d"]).arg(esp_disk)
        .args(["-p", &esp_partition.to_string(),
               "-L", NVRAM_ENTRY_LABEL,
               "-l", "\\EFI\\xen\\xen.efi"])
        .output();
    match created {
        Ok(o) if o.status.success() => log(format!(
            "created {NVRAM_ENTRY_LABEL:?} -> \\EFI\\xen\\xen.efi")),
        Ok(o) => {
            log(format!("efibootmgr -c exit={} — entry not created: {}",
                        o.status, String::from_utf8_lossy(&o.stderr).trim()));
            return;
        }
        Err(e) => { log(format!("efibootmgr -c spawn failed: {e}")); return; }
    }
    // `-c` prepends the new entry to BootOrder — restore the pre-create
    // order so Ubuntu remains the firmware default (sacred rule). If
    // the restore fails we say so LOUDLY: the machine would now default
    // to Xen on unattended reboots.
    if let Some(order) = order_before {
        match Command::new("efibootmgr").args(["-o", &order]).output() {
            Ok(o) if o.status.success() =>
                log(format!("BootOrder restored to {order} (Ubuntu stays default)")),
            Ok(o) => log(format!(
                "WARNING: BootOrder restore FAILED (exit={}) — firmware may now \
                 default to Xen! Fix with: efibootmgr -o {order} ({})",
                o.status, String::from_utf8_lossy(&o.stderr).trim())),
            Err(e) => log(format!(
                "WARNING: BootOrder restore FAILED ({e}) — firmware may now \
                 default to Xen! Fix with: efibootmgr -o {order}")),
        }
    }
}

// ---------------------------------------------------------------------------
// Tests

#[cfg(test)]
mod tests {
    use super::*;
    use crate::thin_dom0_manifest::UserDesktopDisplayMode;

    fn sample_inputs() -> GrubEntryInputs {
        GrubEntryInputs {
            entry_name: "rotten-apple ThinDom0".to_string(),
            boot_fs_uuid: "2048f8be-403d-4cb7-b79a-c821a0daa609".to_string(),
            xen_image: PathBuf::from("xen-4.20-amd64.gz"),
            dom0_kernel: PathBuf::from("rotten-apple/vmlinuz"),
            dom0_initrd: PathBuf::from("rotten-apple/thin-dom0.cpio.gz"),
            dom0_mem_mb: 4096,
            dom0_vcpus: 1,
            user_root_uuid: "9881a7d1-66a6-463d-9433-a7117badbc35".to_string(),
            dom0_pinned_cpu: Some(12),
            framebuffer_gpu_bdf: Some("0000:00:02.0".to_string()),
            display_mode: UserDesktopDisplayMode::ParavirtOnly,
            esp_fs_uuid: Some("B6D5-2FF2".to_string()),
        }
    }

    #[test]
    fn xen_cfg_has_default_and_recovery_sections() {
        let cfg = render_xen_cfg(&sample_inputs());
        assert!(cfg.contains("[global]") && cfg.contains("default=thindom0"),
                "global section must pick thindom0 as default: {cfg}");
        assert!(cfg.contains("[thindom0]") && cfg.contains("[recovery]"),
                "both sections must exist: {cfg}");
    }

    #[test]
    fn xen_cfg_sections_mirror_grub_cmdline_builders() {
        // The whole point of the shared builders: the ESP boot path and
        // the GRUB multiboot2 path carry IDENTICAL cmdlines. Pin the
        // xen.cfg lines to the builders' output verbatim.
        let g = sample_inputs();
        let cfg = render_xen_cfg(&g);
        assert!(cfg.contains(&format!("options={}", xen_options_cmdline(&g, false))));
        assert!(cfg.contains(&format!("options={}", xen_options_cmdline(&g, true))));
        assert!(cfg.contains(&format!("kernel=vmlinuz {}", dom0_kernel_cmdline(&g, false))));
        assert!(cfg.contains(&format!("kernel=vmlinuz {}", dom0_kernel_cmdline(&g, true))));
    }

    #[test]
    fn xen_cfg_has_no_multiboot_placeholder_token() {
        // "placeholder" is the multiboot first-arg convention (image
        // name slot). In xen.cfg it would be parsed as a real Xen or
        // kernel argument — unknown-param noise at best.
        let cfg = render_xen_cfg(&sample_inputs());
        assert!(!cfg.contains("placeholder"),
                "xen.cfg must not carry the multiboot placeholder token: {cfg}");
    }

    #[test]
    fn xen_cfg_recovery_section_is_observable_and_no_autostart() {
        let cfg = render_xen_cfg(&sample_inputs());
        let recovery = cfg.split("[recovery]").nth(1).expect("recovery section");
        assert!(recovery.contains("sync_console=true") && recovery.contains("noreboot"),
                "recovery options must carry sync_console + noreboot: {recovery}");
        assert!(recovery.contains("console=hvc0"),
                "recovery dom0 console must be hvc0 (visible through Xen): {recovery}");
        assert!(recovery.contains("rotten_apple.no_autostart=1"),
                "recovery must not autostart the guest: {recovery}");
    }

    #[test]
    fn xen_cfg_ramdisk_and_relative_paths() {
        // xen.efi resolves paths relative to its own directory — bare
        // filenames, no leading slash, no /boot prefix.
        let cfg = render_xen_cfg(&sample_inputs());
        assert_eq!(cfg.matches("ramdisk=initrd.cpio.gz").count(), 2,
                   "both sections need the ramdisk line: {cfg}");
        assert!(!cfg.contains("kernel=/") && !cfg.contains("ramdisk=/"),
                "ESP paths must be relative to xen.efi's dir: {cfg}");
    }

    #[test]
    fn esp_mount_parsed_from_mountinfo() {
        let info = "\
22 25 0:21 / /sys rw - sysfs sysfs rw
25 1 259:2 / / rw - ext4 /dev/nvme0n1p2 rw
40 25 259:1 / /boot/efi rw - vfat /dev/nvme0n1p1 rw
";
        assert_eq!(esp_mount_device_from_mountinfo(info),
                   Some(PathBuf::from("/dev/nvme0n1p1")));
    }

    #[test]
    fn esp_mount_none_on_bios_hosts() {
        let info = "25 1 259:2 / / rw - ext4 /dev/sda1 rw\n";
        assert_eq!(esp_mount_device_from_mountinfo(info), None);
    }

    #[test]
    fn nvram_detection_requires_label_and_loader_path() {
        // Real efibootmgr shapes from this Dell (2026-07-08).
        let with_entry = "\
BootCurrent: 0003
BootOrder: 0003,0000,0002,0005,0001
Boot0003* Ubuntu\tHD(1,GPT,0e90f3a3)/\\EFI\\ubuntu\\shimx64.efi
Boot0004* rotten-apple Xen (native EFI)\tHD(1,GPT,0e90f3a3)/\\EFI\\xen\\xen.efi
";
        assert!(nvram_has_current_entry(with_entry));
        // Same label pointing somewhere stale — must NOT count.
        let stale = "Boot0004* rotten-apple Xen (native EFI)\tHD(1,GPT,x)/\\EFI\\old\\xen.efi\n";
        assert!(!nvram_has_current_entry(stale));
        assert!(!nvram_has_current_entry("Boot0003* Ubuntu\t...\n"));
    }

    #[test]
    fn boot_order_extracted_verbatim() {
        let out = "BootCurrent: 0003\nTimeout: 5 seconds\nBootOrder: 0003,0000,0002\n";
        assert_eq!(boot_order_value(out), Some("0003,0000,0002".to_string()));
        assert_eq!(boot_order_value("no order here\n"), None);
    }

    #[test]
    fn stage_esp_writes_all_four_files() {
        let tmp = tempfile::tempdir().unwrap();
        let esp = tmp.path().join("esp");
        std::fs::create_dir_all(&esp).unwrap();
        let src = tmp.path().join("src");
        std::fs::create_dir_all(&src).unwrap();
        for (name, bytes) in [("xen.efi", b"XEN" as &[u8]),
                              ("vmlinuz", b"KRN"),
                              ("cpio",    b"RFS")] {
            std::fs::write(src.join(name), bytes).unwrap();
        }
        let inputs = EspStageInputs {
            esp_mount: esp.clone(),
            xen_efi_source: src.join("xen.efi"),
            kernel_source:  src.join("vmlinuz"),
            initrd_source:  src.join("cpio"),
        };
        stage_esp(&inputs, "cfg-body\n", false).unwrap();
        let dir = esp.join(ESP_XEN_DIR);
        assert_eq!(std::fs::read(dir.join("xen.efi")).unwrap(), b"XEN");
        assert_eq!(std::fs::read(dir.join("vmlinuz")).unwrap(), b"KRN");
        assert_eq!(std::fs::read(dir.join("initrd.cpio.gz")).unwrap(), b"RFS");
        assert_eq!(std::fs::read_to_string(dir.join("xen.cfg")).unwrap(), "cfg-body\n");
    }

    #[test]
    fn stage_esp_dry_run_touches_nothing() {
        let tmp = tempfile::tempdir().unwrap();
        let inputs = EspStageInputs {
            esp_mount: tmp.path().join("esp"),
            xen_efi_source: tmp.path().join("missing-xen.efi"),
            kernel_source:  tmp.path().join("missing-vmlinuz"),
            initrd_source:  tmp.path().join("missing-cpio"),
        };
        // Sources don't even exist — dry-run must still succeed and
        // must not create the ESP dir.
        stage_esp(&inputs, "cfg\n", true).unwrap();
        assert!(!tmp.path().join("esp").exists());
    }
}
